{% set version = '0.1-3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-base64enc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/base64enc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/base64enc/base64enc_{{ version }}.tar.gz
  sha256: 6d856d8a364bcdc499a0bf38bfd283b7c743d08f0b288174fba7dbf0a04b688d

build:
  number: 1008
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('base64enc')"           # [not win]
    - "\"%R%\" -e \"library('base64enc')\""  # [win]

about:
  home: http://www.rforge.net/base64enc
  license: GPL-2.0-or-later
  summary: |
    This package provides tools for handling base64 encoding. It is more flexible than
    the orphaned base64 package.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
