appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FG4qSooroWalbcbzqUelZjthJQc4Rt9mVvJBhkLzwr46X2U90dKSJDUWcz8aluPXCmHgch67dFKYqgmZuEF9sIn5ZOkMIecPIh/mP/t/QK4UeqPYpMAbzmsMMC0ax076TOzf51RdvXrlt5YRuVHR/lLz0QxspWsl61hm1ny03ApDZwX/bxS91sf0rSK5X7ZS08K9enSv1Y685iHK7Yk6umceKvu+BnALmHo/nyzZpP8X9aWnQUTgTaWVA1Khzt2AeK5nt7B4MvotBIEBs9OFfEXTKj0xMX4rL+VrIchLFpGb/niibJiPZ7B+2i5AUR/eYfCRSixr+2ADENAhCCaETRJwwe7Fuw7sIVAX0DVON3yQXfPS4diT/hMKp0ouWz7daDsrht0GrlzhEpfCI5CGBwqESyWAwYSZEzx7hJseSJ/0yDFDnBMzYrUvmjHUai9C736zKohUYpBdSANZSqJKRSsjYQvdkM2M3XCk4VWL1w6SjdOEcCS2Bw0FWr60hWMm88hiozWT2Qx53yiKh8W4ERn2liC58tDd0tUbhqGHjBCLm2dW87NH9lbKupX+GV5TA/LHUue2vWcNJbIJE1/Uhf3U16FzLhYGMaXv5SFXOas/M/EsXkHxZQ9xqaM43cyePVP51K35Kq2DsByP5yyRmk2NLymW/ygM09FuP663r1g=}
